enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 2
remove-rv-integrations-checks = true
compression-level = 6

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/flixztried/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended - inotia00"
arch = "arm64-v8a"
build-mode = "both"
version = "8.30.54"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "ReVanced Extended - anddea"
arch = "arm64-v8a"
build-mode = "both"
version = "20.05.46"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube'"

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram"
patches-source = "revanced/revanced-patches"
integrations-source = "revanced/revanced-integrations"
rv-brand = "ReVanced"
arch = "arm64-v8a"
build-mode = "both"
version = "auto"
# excluded-patches = ""
